[GROQ]
api_key = "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"

[MSSQL]
host = "database-1.ctuq4yyqsjz3.ap-south-1.rds.amazonaws.com"
database = "testing"
user = "admin"
password = "8qCXdHLzExXb5.=-EaC9uGluGSxx%zM&"
db_excel = "excel_data_storage"
db_login = "login_db"
admin= "admin"
admin_password= "password123"
